# Generated by Django 5.1.6 on 2025-10-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='transferred_by',
        ),
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transfers_out', to='core.location')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transfers_in', to='core.location')),
            ],
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferbatch'),
            preserve_default=False,
        ),
    ]
