# Generated by Django 5.1.6 on 2025-10-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stocktransfer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.transferbatch'),
        ),
    ]
