# Generated by Django 4.2.24 on 2025-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_saleorder_remove_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('ZAR', 'South African Rand'), ('XAF', 'Central African CFA Franc'), ('XOF', 'West African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira')], default='UGX', max_length=3),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('receipt', 'Receipt'), ('delivery_note', 'Delivery Note'), ('credit_note', 'Credit Note')], default='invoice', max_length=20),
        ),
    ]
