# Generated by Django 5.1.6 on 2025-10-31 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_sale_currency_alter_sale_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Teba Inventory', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID/VAT Number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('quotation_prefix', models.CharField(default='QUO', max_length=10)),
                ('receipt_prefix', models.CharField(default='REC', max_length=10)),
                ('invoice_footer', models.TextField(blank=True, help_text='Footer text for invoices', null=True)),
                ('quotation_footer', models.TextField(blank=True, help_text='Footer text for quotations', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
