# Generated by Django 5.1.6 on 2025-11-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_debttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
